substitutions:
  name: car-presence-workshop
  friendly_name: "Car Presence Workshop"
  board: d1_mini

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: ${board}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${friendly_name} AP
    password: !secret car_presence_workshop_ap_password

captive_portal:
  
logger:

api:
  encryption:
    key: !secret car_presence_workshop_api_encryption_key

ota:
  - platform: esphome
    password: !secret car_presence_workshop_ota_password

text_sensor:
  - platform: version
    name: ESPHome Version - ${friendly_name}

  - platform: wifi_info
    ip_address: 
      name: IP - ${friendly_name}
    mac_address:
      name: MAC - ${friendly_name}

# HC-SR04 Ultrasonic Sensor Configuration
sensor:
  - platform: ultrasonic
    id: ultrasonic_sensor
    internal: true
    trigger_pin: D1
    echo_pin: D2
    update_interval: 1s
    filters:
      - lambda: |-
          return isnan(x) ? 4.0 : x;    

number:
  - platform: template
    name: "Minimum Distance"
    id: min_distance
    unit_of_measurement: "m"
    min_value: 0.1
    max_value: 1.0
    step: 0.1
    optimistic: true
    initial_value: 0.6

  - platform: template
    name: "Maximum Distance"
    id: max_distance
    unit_of_measurement: "m"
    min_value: 1.1
    max_value: 5.0
    step: 0.1
    optimistic: true
    initial_value: 1.1

  - platform: template
    name: "Detection Cycles"
    id: detection_cycles
    unit_of_measurement: "cycles"
    min_value: 1
    max_value: 20
    step: 1
    optimistic: true
    initial_value: 12    
          
binary_sensor:
  - platform: template
    id: car_presence
    name: "Car Presence"
    icon: mdi:car
    device_class: occupancy
    lambda: |-
      if (id(distance_in_range).state) {
        return true;
      } else {
        return false;
      }

  - platform: template
    id: distance_in_range
    internal: true

# Interval filter to check for a range condition lasting more than 2 minutes
interval:
  - interval: 10s
    then:
      - lambda: |-
          static int car_detected = 0;
          float dist = id(ultrasonic_sensor).state;
          float min_dist = id(min_distance).state;
          float max_dist = id(max_distance).state;
          int max_cycles = (int) id(detection_cycles).state;
          if (dist >= min_dist && dist <= max_dist) {
            if(car_detected <= max_cycles) {
              car_detected++;
              if(car_detected == max_cycles) {
                id(distance_in_range).publish_state(true);
              }
            }
          }else {
            if(car_detected >= -1){
              car_detected--;
              if(car_detected == 0) {
                id(distance_in_range).publish_state(false);
              }
            }
          }