substitutions:
  name: car-presence-workshop
  friendly_name: "Car Presence Workshop"
  board: d1_mini

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: ${board}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${friendly_name} AP
    password: !secret car_presence_workshop_ap_password

captive_portal:
  
logger:

api:
  encryption:
    key: !secret car_presence_workshop_api_encryption_key

ota:
  - platform: esphome
    password: !secret car_presence_workshop_ota_password

text_sensor:
  - platform: version
    name: ESPHome Version - ${friendly_name}

  - platform: wifi_info
    ip_address: 
      name: IP - ${friendly_name}
    mac_address:
      name: MAC - ${friendly_name}

# HC-SR04 Ultrasonic Sensor Configuration
sensor:
  - platform: ultrasonic
    id: ultrasonic_sensor
    internal: true
    trigger_pin: D1
    echo_pin: D2
    update_interval: 1s
          
binary_sensor:
  - platform: template
    id: car_presence
    name: "Car Presence"
    icon: mdi:car
    device_class: occupancy
    lambda: |-
      if (id(distance_in_range).state) {
        return true;
      } else {
        return false;
      }

  - platform: template
    id: distance_in_range
    internal: true

# Interval filter to check for a range condition lasting more than 2 minutes
interval:
  - interval: 10s
    then:
      - lambda: |-
          static int car_detected = 0;
          float dist = id(ultrasonic_sensor).state;
          if (dist >= 0.6 && dist <= 1) {
            if(car_detected <= 11) {
              car_detected++;
              if(car_detected == 12) {
                id(distance_in_range).publish_state(true);
              }
            }
          }else {
            if(car_detected >= -1){
              car_detected--;
              if(car_detected == 0) {
                id(distance_in_range).publish_state(false);
              }
            }
          }











    